[phases.setup]
nixPkgs = ["python39", "gcc", "gcc.cc.lib"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "cd backend && gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
