[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
PORT = "8001"
HOST = "0.0.0.0"
USE_SUPABASE = "true"
DEBUG = "false"

